import type {SettingsTabDefinition} from '@/types/settings'
const f=(key:string,label:string,type:any='text',extra:Record<string,unknown>={})=>({key,label,type,...extra})
export const settingsTabs:SettingsTabDefinition[]=[
 {slug:'tong-quan',group:'general.site',title:'Tổng quan',description:'Thông tin chung, ngôn ngữ, tiền tệ và chế độ vận hành website.',previewUrl:'/',fields:[f('siteName','Tên website'),f('companyName','Tên công ty'),f('shortName','Tên viết tắt'),f('slogan','Slogan'),f('description','Mô tả doanh nghiệp','textarea'),f('language','Ngôn ngữ','select',{options:[{label:'Tiếng Việt',value:'vi'}]}),f('timezone','Múi giờ'),f('currency','Đơn vị tiền tệ'),f('currencySymbol','Ký hiệu tiền tệ'),f('maintenanceMode','Chế độ bảo trì','switch'),f('maintenanceMessage','Nội dung bảo trì','textarea'),f('systemNotificationEmail','Email nhận thông báo')]},
 {slug:'thuong-hieu',group:'brand.identity',title:'Thương hiệu',description:'Logo, màu sắc và kiểu chữ nhận diện thương hiệu.',fields:[f('logoId','Logo chính','media'),f('logoDarkId','Logo nền tối','media'),f('logoLightId','Logo nền sáng','media'),f('faviconId','Favicon','media'),f('ogDefaultImageId','Ảnh Open Graph','media'),f('brandColor','Màu chính','color'),f('accentColor','Màu nhấn','color'),f('backgroundColor','Màu nền','color'),f('fontFamily','Font chính','select',{options:[{label:'Be Vietnam Pro',value:'Be Vietnam Pro'}]}),f('brandName','Tên thương hiệu'),f('slogan','Slogan')]},
 {slug:'dau-trang',group:'header.config',title:'Đầu trang',description:'Thanh thông báo, tiện ích, menu và nút hành động trên Header.',previewUrl:'/',fields:[f('topNoticeEnabled','Bật thanh thông báo','switch'),f('topNoticeText','Nội dung thông báo'),f('topNoticeIcon','Icon thông báo'),f('topNoticeBackgroundColor','Màu nền thông báo','color'),f('topNoticeTextColor','Màu chữ thông báo','color'),f('stickyHeader','Cố định khi cuộn','switch'),f('showLogo','Hiển thị logo','switch'),f('showTagline','Hiển thị slogan','switch'),f('showSearch','Hiển thị tìm kiếm','switch'),f('showAccount','Hiển thị tài khoản','switch'),f('showWishlist','Hiển thị yêu thích','switch'),f('showCompare','Hiển thị so sánh','switch'),f('showCart','Hiển thị giỏ hàng','switch'),f('primaryCtaLabel','Nút CTA chính'),f('primaryCtaUrl','Liên kết CTA','url')]},
 {slug:'chan-trang',group:'footer.config',title:'Chân trang',description:'Nội dung, liên hệ, nhận tin và các liên kết cuối trang.',previewUrl:'/',fields:[f('description','Mô tả doanh nghiệp','textarea'),f('showHotline','Hiển thị hotline','switch'),f('showEmail','Hiển thị email','switch'),f('showAddress','Hiển thị địa chỉ','switch'),f('showSocial','Hiển thị mạng xã hội','switch'),f('showNewsletter','Bật đăng ký nhận tin','switch'),f('newsletterTitle','Tiêu đề nhận tin'),f('newsletterDescription','Mô tả nhận tin','textarea'),f('newsletterPlaceholder','Placeholder email'),f('newsletterButtonLabel','Nhãn nút đăng ký'),f('copyrightText','Dòng bản quyền'),f('licenseText','Thông tin giấy phép','textarea'),f('bottomLinks','Liên kết phụ','repeater')]},
 {slug:'trang-chu',group:'home.config',title:'Trang chủ',description:'Nội dung, hình ảnh và trạng thái các khu vực trên trang chủ.',previewUrl:'/',fields:[f('heroEnabled','Bật Hero','switch'),f('heroSubtitle','Nhãn nhỏ'),f('heroTitle','Tiêu đề Hero'),f('heroDescription','Mô tả Hero','textarea'),f('heroImageId','Ảnh Hero','media'),f('heroPrimaryCtaLabel','Nút chính'),f('heroPrimaryCtaUrl','Link nút chính','url'),f('featuredProductsEnabled','Bật sản phẩm nổi bật','switch'),f('featuredProductsTitle','Tiêu đề sản phẩm nổi bật'),f('featuredProductsLimit','Số sản phẩm','number',{min:1,max:24}),f('categoriesEnabled','Bật danh mục','switch'),f('statsEnabled','Bật thống kê','switch'),f('servicesEnabled','Bật dịch vụ','switch'),f('testimonialsEnabled','Bật đánh giá','switch'),f('newsEnabled','Bật tin tức','switch'),f('newsLimit','Số bài viết','number',{min:1,max:24})]},
 {slug:'san-pham',group:'products.config',title:'Sản phẩm',description:'Cấu hình trang danh sách sản phẩm, bộ lọc và thẻ sản phẩm.',previewUrl:'/san-pham',fields:[f('listingTitle','Tiêu đề trang'),f('listingDescription','Mô tả trang','textarea'),f('categoryBannerDefaultId','Banner mặc định','media'),f('productsPerPage','Số sản phẩm mỗi trang','number',{min:1,max:100}),f('defaultSort','Sắp xếp mặc định'),f('showPrice','Hiển thị giá','switch'),f('priceFallbackLabel','Nhãn khi không có giá'),f('showWishlist','Hiển thị yêu thích','switch'),f('showCompare','Hiển thị so sánh','switch'),f('showQuoteButton','Hiển thị báo giá','switch')]},
 {slug:'dich-vu',group:'services.config',title:'Dịch vụ',description:'Trang danh sách và chi tiết dịch vụ.',previewUrl:'/dich-vu',fields:[f('listingTitle','Tiêu đề'),f('listingDescription','Mô tả','textarea'),f('showFaq','Hiển thị FAQ','switch'),f('showProcess','Hiển thị quy trình','switch'),f('showContactForm','Hiển thị form liên hệ','switch'),f('defaultCtaLabel','Nhãn CTA'),f('defaultCtaUrl','Liên kết CTA','url')]},
 {slug:'tin-tuc',group:'posts.config',title:'Tin tức',description:'Danh sách bài viết và cấu hình trang chi tiết.',previewUrl:'/tin-tuc',fields:[f('listingTitle','Tiêu đề'),f('listingDescription','Mô tả','textarea'),f('postsPerPage','Số bài mỗi trang','number',{min:1,max:100}),f('showAuthor','Hiển thị tác giả','switch'),f('showPublishedDate','Hiển thị ngày đăng','switch'),f('showRelatedPosts','Hiển thị bài liên quan','switch'),f('relatedPostsLimit','Số bài liên quan','number',{min:1,max:12})]},
 {slug:'lien-he',group:'contact.info',title:'Liên hệ',description:'Thông tin liên hệ dùng chung cho Header, Footer và trang liên hệ.',previewUrl:'/lien-he',fields:[f('hotline','Hotline'),f('hotlineSecondary','Hotline phụ'),f('zaloPhone','Số Zalo'),f('email','Email'),f('salesEmail','Email kinh doanh'),f('supportEmail','Email hỗ trợ'),f('address','Địa chỉ','textarea'),f('showroomAddress','Địa chỉ showroom','textarea'),f('warehouseAddress','Địa chỉ kho','textarea'),f('workingHours','Giờ làm việc'),f('googleMapUrl','Google Map','url'),f('taxCode','Mã số thuế')]},
 {slug:'so-sanh',group:'products.config',title:'So sánh',description:'Giới hạn, chia sẻ và nội dung trang so sánh sản phẩm.',previewUrl:'/so-sanh',fields:[f('enableCompare','Bật so sánh','switch'),f('compareMaxItems','Số sản phẩm tối đa','number',{min:2,max:4}),f('compareFloatingTrayEnabled','Bật thanh so sánh nổi','switch'),f('compareAllowDifferentGroups','Cho phép khác nhóm','switch'),f('compareShareEnabled','Cho phép chia sẻ link','switch'),f('compareShowEqualRowsByDefault','Hiển thị điểm giống nhau','switch'),f('compareAddAllToQuoteEnabled','Nút thêm tất cả vào báo giá','switch'),f('compareEmptyTitle','Thông báo danh sách trống'),f('compareButtonLabel','Nhãn nút so sánh')]},
 {slug:'popup-banner',group:'popup.config',title:'Popup và Banner',description:'Popup chiến dịch và lựa chọn banner theo vị trí.',fields:[f('enabled','Bật popup','switch'),f('type','Loại popup'),f('title','Tiêu đề'),f('description','Mô tả','textarea'),f('imageId','Ảnh popup','media'),f('ctaLabel','Nhãn nút'),f('ctaUrl','Liên kết','url'),f('delaySeconds','Thời gian trì hoãn','number',{min:0,max:300}),f('showOncePerSession','Một lần mỗi phiên','switch')]},
 {slug:'seo',group:'seo.default',title:'SEO',description:'Metadata, tên miền, Open Graph và công cụ tìm kiếm.',fields:[f('siteName','Tên website'),f('defaultTitle','Tiêu đề mặc định'),f('titleTemplate','Mẫu tiêu đề'),f('defaultDescription','Mô tả mặc định','textarea'),f('siteUrl','Tên miền chính','url'),f('defaultOgImageId','Ảnh Open Graph','media'),f('faviconId','Favicon','media'),f('twitterCard','Twitter Card'),f('robotsIndex','Cho phép lập chỉ mục','switch'),f('robotsFollow','Cho phép theo liên kết','switch'),f('googleVerificationCode','Search Console')]},
 {slug:'tich-hop',group:'integrations.tracking',title:'Tích hợp',description:'Dịch vụ đo lường và kết nối bên thứ ba.',fields:[f('googleAnalyticsId','Google Analytics ID'),f('googleTagManagerId','Google Tag Manager ID'),f('facebookPixelId','Facebook Pixel ID'),f('googleSearchConsoleCode','Google Search Console')]},
 {slug:'nang-cao',group:'advanced.config',title:'Nâng cao',description:'Cache, sitemap, robots và chế độ chẩn đoán.',fields:[f('enableCache','Bật cache','switch'),f('cacheTtlSeconds','Thời gian cache','number',{min:0}),f('enableDebugMode','Bật debug','switch'),f('enableSitemap','Bật sitemap','switch'),f('enableRobots','Bật robots','switch'),f('defaultNoImageId','Ảnh mặc định khi thiếu','media'),f('lazyLoadImages','Lazy load ảnh','switch')]},
]
const placeholders=[['gioi-thieu','about.config','Giới thiệu','Nội dung doanh nghiệp, lịch sử, tầm nhìn và giá trị cốt lõi.','/gioi-thieu'],['chi-tiet-san-pham','product-detail.config','Chi tiết sản phẩm','Thành phần, CTA và nội dung trang chi tiết sản phẩm.','/san-pham'],['catalogue','catalogue.config','Catalogue','Tệp catalogue, ảnh bìa và nội dung tải xuống.','/catalogue'],['ho-tro','support.config','Hỗ trợ','Hướng dẫn mua hàng, bảo hành, đổi trả, thanh toán và FAQ.','/ho-tro'],['tai-khoan','account.config','Tài khoản','Đăng nhập, đăng ký và nội dung khu vực khách hàng.','/tai-khoan'],['gio-hang-bao-gia','quote-cart.config','Giỏ hàng và báo giá','Nhãn, trạng thái và quy trình yêu cầu báo giá.','/gio-hang'],['tim-kiem','search.config','Tìm kiếm','Nguồn tìm kiếm, gợi ý và nội dung khi không có kết quả.','/san-pham']]
for(const [slug,group,title,description,previewUrl] of placeholders)settingsTabs.splice(settingsTabs.length-4,0,{slug,group,title,description,previewUrl,fields:[f('enabled','Bật chức năng','switch'),f('pageTitle','Tiêu đề trang'),f('pageDescription','Mô tả trang','textarea'),f('emptyMessage','Thông báo khi trống','textarea')]})
export const settingsTabBySlug=new Map(settingsTabs.map(tab=>[tab.slug,tab]))
